### ISSUE TITLE
Vimvaldi references something in abjad that isn't there

### ISSUE THREAD

**Issue by n8chz** [xiaoxiae/Vimvaldi#5]
```
Traceback (most recent call last):
  File "/home/lori/.local/bin/vimvaldi", line 5, in <module>
    from vimvaldi.__init__ import run
  File "/home/lori/.local/lib/python3.10/site-packages/vimvaldi/__init__.py", line 8, in <module>
    from vimvaldi.music import *
  File "/home/lori/.local/lib/python3.10/site-packages/vimvaldi/music.py", line 6, in <module>
    def from_duration(cls, duration: abjad.utilities.Duration) -> str:
AttributeError: module 'abjad' has no attribute 'utilities'
```

**Comment by xiaoxiae** [comment]
I'm sorry, it looks like the Abjad API has changed since I updated this app (`abjad.utilities.Duration` became `abjad.duration.Duration`).
